### ISSUE TITLE
哥，架设好之后，有办法接入VSCode里面的cline插件或者continue插件么？

### ISSUE THREAD

**Issue by liuzhiyuan562** [formzs/poe-to-gpt#10]
想在VSCode里面用claude，用cline里面的openai conpatible，然后访问，这边一直是400，[GIN] 2024/11/25 - 10:50:28 | 400 |     939.746µs |       127.0.0.1 | POST     "/v1/chat/completions"
![image](https://github.com/user-attachments/assets/abffaf8f-81c5-4829-ac45-f85c22ac821a)
![image](https://github.com/user-attachments/assets/77660982-0220-4ce3-8b6a-bc1ae73366c6)

**Comment by formzs** [comment]
经尝试，此方法效果欠佳。建议在这种高消耗的场景下，更换其他方法。
