### ISSUE TITLE
返回数据最高203个字符 finish_reason:"stop"

### ISSUE THREAD

**Issue by imK3** [formzs/poe-to-gpt#17]
如题，这是什么原因？返回后就是... stop了每次203个字符。
![image](https://github.com/user-attachments/assets/f2abcadb-e8fc-4b6f-b2d8-c3c551f486b1)

**Comment by imK3** [comment]
看到代码了...为啥限制200.

**Comment by imK3** [comment]
![image](https://github.com/user-attachments/assets/cbd1e65c-c14b-4383-89e2-cbf503a19f22)

**Comment by formzs** [comment]
已进行更改，请再次进行尝试。
