### ISSUE TITLE
api.py的代码问题

### ISSUE THREAD

**Issue by fkx816** [formzs/poe-to-gpt#2]
运行poe-openai-proxy.exe会提示INFO: registering client: "failed: asyncio.run() cannot be called from a running event loop"
py.exe会提示INFO:root:Failed to connect to poe due to asyncio.run() cannot be called from a running event loop，应该是api.py部分代码有问题

**Comment by formzs** [comment]
对代码进行了相应修改，烦请再度尝试，以确认是否仍会出现此提示。

**Comment by fkx816** [comment]
> 对代码进行了相应修改，烦请再度尝试，以确认是否仍会出现此提示。

运行成功了，谢谢大佬。顺便给readme捉个虫，”This is a tool that converts the API key provided by Poe (Path of Exile) official website into a compatible OpenAI API key.“应该是Poe(Poe.com),不是(Path of Exile)。

**Comment by fkx816** [comment]
再次感谢大佬
