### ISSUE TITLE
能不能用cookie的方式让非订阅用户也能用poe api?

### ISSUE THREAD

**Issue by reccea** [formzs/poe-to-gpt#3]
能不能类似 [poe-api-wrapper](https://github.com/snowby666/poe-api-wrapper) 的方式，用cookie的方式，让非订阅用户也能用到兼容openai的poe api?

**Comment by formzs** [comment]
目前尚无此计划。

**Comment by daishuge** [comment]
非订阅者的点数估计不够玩api的吧
