### ISSUE TITLE
[BUG] Proxy Settings in config.toml Are Not Taking Effect

### ISSUE THREAD

**Issue by MermengM** [formzs/poe-to-gpt#4]
# Description: 
在config.toml中设置proxy不生效，看了下external/api.py中似乎只有第20行取了proxy = config["proxy"]，没有后续操作。

**Comment by MermengM** [comment]
\# 暂时解决方案：
\# external/api.py
`proxy = config["proxy"]`
`# 设置代理环境变量`
`if proxy:`
`    os.environ['HTTP_PROXY'] = proxy`  
`    os.environ['HTTPS_PROXY'] = proxy`

**Comment by formzs** [comment]
新增了代理配置，烦请测试。

**Comment by MermengM** [comment]
经过测试，代理配置可以使用。
