### ISSUE TITLE
lobeChat测试，日志有回复，客户端显示不行

### ISSUE THREAD

**Issue by wangjiaming1503** [formzs/poe-to-gpt#8]
![image](https://github.com/user-attachments/assets/cafbd640-532b-4031-8283-8f0ef26067c3)

||>User:
你好啊
||>Assistant:
...
||>User:
我今天不开心
||>Assistant:
INFO: Stream using bot GPT-4o-Mini
[GIN] 2024/09/08 - 10:23:03 | 200 |      11.526µs |      172.22.0.1 | OPTIONS  "/v1/chat/completions"
[GIN] 2024/09/08 - 10:23:03 | 500 |      62.408µs |      172.22.0.1 | POST     "/v1/chat/completions"
[GIN] 2024/09/08 - 10:23:04 | 200 |      14.944µs |      172.22.0.1 | OPTIONS  "/v1/chat/completions"
[GIN] 2024/09/08 - 10:23:04 | 500 |      75.732µs |      172.22.0.1 | POST     "/v1/chat/completions"
INFO: Rev:  
INFO: Rev:  很
INFO: Rev:  抱
INFO: Rev:  歉
INFO: Rev:  听
INFO: Rev:  到
INFO: Rev:  你
INFO: Rev:  今天
INFO: Rev:  不
INFO: Rev:  开心
INFO: Rev:  。
INFO: Rev:  有什么
INFO: Rev:  特别
INFO: Rev:  的
INFO: Rev:  事情
INFO: Rev:  让
INFO: Rev:  你
INFO: Rev:  感
INFO: Rev:  到
INFO: Rev:  不
INFO: Rev:  快乐
INFO: Rev:  吗
INFO: Rev:  ？
INFO: Rev:  如果
INFO: Rev:  你
INFO: Rev:  愿
INFO: Rev:  意
INFO: Rev:  分享
INFO: Rev:  ，我
INFO: Rev:  在
INFO: Rev:  这里
INFO: Rev:  倾
INFO: Rev:  听
INFO: Rev:  。
INFO: Rev:  
ERROR: write tcp 172.22.0.3:3700->172.22.0.1:35180: write: broken pipe
ERROR: write tcp 172.22.0.3:3700->172.22.0.1:35180: write: broken pipe
ERROR: write tcp 172.22.0.3:3700->172.22.0.1:35180: write: broken pipe
ERROR: write tcp 172.22.0.3:3700->172.22.0.1:35180: write: broken pipe
ERROR: write tcp 172.22.0.3:3700->172.22.0.1:35180: write: broken pipe
ERROR: write tcp 172.22.0.3:3700->172.22.0.1:35180: write: broken pipe
ERROR: write tcp 172.22.0.3:3700->172.22.0.1:35180: write: broken pipe
ERROR: write tcp 172.22.0.3:3700->172.22.0.1:35180: write: broken pipe
ERROR: write tcp 172.22.0.3:3700->172.22.0.1:35180: write: broken pipe
ERROR: write tcp 172.22.0.3:3700->172.22.0.1:35180: write: broken pipe
ERROR: write tcp 172.22.0.3:3700->172.22.0.1:35180: write: broken pipe
INFO: Rev:  
ERROR: write tcp 172.22.0.3:3700->172.22.0.1:35180: write: broken pipe
ERROR: write tcp 172.22.0.3:3700->172.22.0.1:35180: write: broken pipe
ERROR: write tcp 172.22.0.3:3700->172.22.0.1:35180: write: broken pipe
[GIN] 2024/09/08 - 10:23:12 | 200 |   8.52165717s |      172.22.0.1 | POST     "/v1/chat/completions"
[GIN] 2024/09/08 - 10:36:37 | 200 |    3.036515ms |      172.22.0.1 | OPTIONS  "/v1/chat/completions"

**Comment by formzs** [comment]
疑似 LobeChat 与 API 服务器之间网络连接不通畅。
